TwentyktoThirtyk/urls.py
from django.urls import path
from django.conf.urls import url

from .views import \
    (
    ProductListView,\
    ProductDetailSlugView,
    Twentyk_to_Thirtyk_Mobile_product_upload,
     )

urlpatterns = [
    url(r'^$',ProductListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name="detail"),

]

carts/urls.py
from django.http import request
from django.urls import path
from django.conf.urls import url

from .views import \
    (
    cart_home,\
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    url(r'^$',cart_home, name="home"),
    url(r'^checkout/success/$', checkout_done_view, name="success"),
    url(r'^checkout/$',checkout_home, name="checkout"),
    url(r'^update/$', cart_update, name="update"),


]

ecommerce/urls.py
from django.contrib import admin

from django.urls import path
from django.conf.urls import  url

from django.conf import settings
from django.conf.urls.static import static,settings

from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from products.views import \
    (ProductListView,\
    product_list_view,\
    ProductDetailView,\
    product_detail_view,\
    ProductFeaturedDetailView,\
    ProductFeaturedListView,\
    ProductDetailSlugView)

from product.views import \
    (ProductListView,\
    product_list_view,\
    ProductDetailView,\
    product_detail_view,\
    ProductFeaturedDetailView,\
    ProductFeaturedListView,\
    ProductDetailSlugView)

from pproducts.views import product_upload,product_list_view,product_detail_view

from aproducts.views import aproduct_upload,product_list_view,product_detail_view

from samsungproducts.views import sproduct_upload,product_list_view,product_detail_view
from huaweiproducts.views import huaweiproduct_upload,product_list_view,product_detail_view





from carts.views import cart_home

from accounts.views import login_page,register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page,about_page,contact_page,cart_page

urlpatterns = [
    url(r'^$',home_page, name="home"),
    url(r'^about/$',about_page, name="about"),
    url(r'^contact/$',contact_page, name="contact"),
    url(r'^login/$',login_page, name="login"),
    url(r'^checkout/address/create/$', checkout_address_create_view, name="checkout_address_create"),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name="checkout_address_reuse"),
    url(r'^register/guest/$', guest_register_view, name="guest_register"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^cart/$',cart_home, name="cart"),
    url(r'^cart/', include(("carts.urls", "carts"), namespace="cart")),
    url(r'^register/$',register_page, name="register"),
    url(r'^bootstrap/$',TemplateView.as_view(template_name="bootstrap/example.html")),
    url(r'^products/',include(("products.urls","products"), namespace = "products")),
    url(r'^product/', include(("product.urls", "product"), namespace="product")),
    url(r'^accessories/', include(("accessories.urls", "accessories"), namespace="accessories")),
    url(r'^pproducts/', include(("pproducts.urls", "pproducts"), namespace="pproducts")),
    url(r'^aproducts/', include(("aproducts.urls", "aproducts"), namespace="aproducts")),
    url(r'^samsungproducts/', include(("samsungproducts.urls", "samsungproducts"), namespace="samsungproducts")),
    url(r'^huaweiproducts/', include(("huaweiproducts.urls", "huaweiproducts"), namespace="huaweiproducts")),
    url(r'^1_GB_Mobiles/', include(("One_GB_Mobiles.urls", "One_GB_Mobiles"), namespace="One_GB_Mobiles")),
    url(r'^Two_GB_Mobiles/', include(("Two_GB_Mobiles.urls", "Two_GB_Mobiles"), namespace="Two_GB_Mobiles")),
    url(r'^Three_GB_Mobiles/', include(("Three_GB_Mobiles.urls", "Three_GB_Mobiles"), namespace="Three_GB_Mobiles")),

    url(r'^ratings/', include(('star_ratings.urls', "star_ratings"), namespace='ratings' )),

    url(r'^FivektoTenk/', include(("FivektoTenk.urls", "FivektoTenk"), namespace="FivektoTenk")),
    url(r'^TenktoTwentyk/', include(("TenktoTwentyk.urls", "TenktoTwentyk"), namespace="TenktoTwentyk")),
    url(r'^TwentyktoThirtyk/', include(("TwentyktoThirtyk.urls", "TwentyktoThirtyk"), namespace="TwentyktoThirtyk")),

    url(r'^FiveMPMobile/', include(("FiveMPMobile.urls", "FiveMPMobile"), namespace="FiveMPMobile")),
    url(r'^EightMPMobile/', include(("EightMPMobile.urls", "EightMPMobile"), namespace="EightMPMobile")),
    url(r'^TwelveMPMobile/', include(("TwelveMPMobile.urls", "TwelveMPMobile"), namespace="TwelveMPMobile")),


    url(r'^search/', include(("search.urls", "search"), namespace="search")),
    url(r'^searchprice/', include(("searchprice.urls", "searchprice"), namespace="searchprice")),
    url(r'^searchram/', include(("searchram.urls", "searchram"), namespace="searchram")),
    url(r'^searchknowledge/', include(("searchknowledge.urls", "searchknowledge"), namespace="searchknowledge")),


    path('upload-csv/', product_upload, name="product_upload"),
    path('upload-apple-csv/', aproduct_upload, name="aproduct_upload"),
    path('upload-samsung-csv/', sproduct_upload, name="sproduct_upload"),
    path('upload-huawei-csv/', huaweiproduct_upload, name="huaweiproduct_upload"),
    # path('upload-1GB-csv/', One_GB_Mobile_product_upload, name="One_GB_Mobile_product_upload"),

    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/$',ProductListView.as_view()),
    # url(r'^products-fbv/$',product_list_view),
    # url(r'^products/(?P<pk>\d+)/$',ProductDetailView.as_view()),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TwentyktoThirtyk/models.py
import random
import os
from django.db import models
from django.urls import reverse

# Create your models here.
from django.db.models.signals import pre_save, post_save
from ecommerce.utils import unique_slug_generator

def get_filename_ext(filename):
    base_name=os.path.basename(filename)
    name, ext = os.path.splitext(filename)
    return name,ext

def upload_image_path(instance,filename):
    print(instance)
    print(filename)
    new_filename=random.randint(1,39321457854)
    name,ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
    return "TwentyktoThirtyk/{new_filename}/{final_filename}".format(new_filename=filename, final_filename=final_filename)

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter()
    def featured(self):
        return self.filter()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    # def all(self):
    #     return self.get_queryset().active()
    #
    # def featured(self):
    #     return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id = id)
        if qs.count() == 1:
            return qs.first()
        return None

class TwentyktoThirtyk_Mobile(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)
    price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    Charging = models.TextField(default="good speakers")
    Torch = models.TextField(default="Yes")
    Games = models.TextField(default="built-in + downloadable")
    Messaging = models.TextField(default=", SMS (threaded view), MMS, Email, Push Email")
    Browser = models.TextField(default="HTML5")
    Audio = models.TextField(default="3.5mm audio jack, MP4/WMV/H.264 player")
    Data = models.TextField(default="GPRS, Edge, 3G (HSPA 42.2/5.76 Mbps), 4G (LTE-A (2CA) Cat6 300/50 Mbps")
    NFC = models.TextField(default="Yes")
    USB = models.TextField(default="microUSB 2.0")
    GPS = models.TextField(default="Yes + A-GPS support & Glonass, BDS, GALILEO")
    Bluetooth = models.TextField(default="None")
    Wifi = models.TextField(default="Wi-Fi 802.11 a/b/g/n/ac, dual-band, hotspot")
    Front = models.TextField(default="13 MP, f/1.9, LED flash")
    Main = models.TextField(default="8MP")
    card = models.TextField(default="Yes")
    BuiltIn = models.TextField(default="16GB Built-in")
    Features = models.TextField(default="None")
    Protection = models.TextField(default="Yes")
    Resolution = models.TextField(default="720 x 1280 Pixels (~282 PPI) ")
    Size = models.TextField(default="5.5 inches")
    Technology = models.TextField(default="None")
    GPU = models.TextField(default="Mali-T830MP2 ")
    Chipset = models.TextField(default="None")
    CPU = models.TextField(default="None")
    FourGBand = models.TextField(default="LTE")
    ThreeGBand = models.TextField(default="HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 ")
    TwoGBand = models.TextField(default="SIM1: GSM 850 / 900 / 1800 / 1900 SIM2: GSM 850 / 900 / 1800 / 1900  ")
    Color = models.TextField(default="Silver, Space Gray, Gold")
    SIM = models.TextField(default="Single SIM (Nano-SIM)  ")
    Weight = models.TextField(default="148g")
    Dimension = models.TextField(default="146.2 x 71.3 x 8 mm")
    UIBuild = models.TextField(default="TouchWiz UI")
    OperatingSystem = models.TextField(default="Android v7.1 Nougat")
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image1 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image2 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    Review_count = models.TextField(default="90")
    Average_Rating = models.TextField(default=" 4")
    Reviews = models.TextField(default="None")
    Ram = models.TextField(default="2GB")




    # description = models.TextField()
    # featured = models.BooleanField(default=False)
    # active = models.BooleanField(default=True)
    # timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def get_absolute_url(self):
        #return "/products/{slug}".format(slug=self.slug)
        return  reverse("TwentyktoThirtyk:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance , *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=TwentyktoThirtyk_Mobile)

TwentyktoThirtyk/views.py
import csv, io
# from django.views import ListView
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import permission_required



# Create your views here.
from carts.models import Cart
from .models import TwentyktoThirtyk_Mobile

class ProductFeaturedListView(ListView):
    template_name = "TwentyktoThirtyk/list.html"

    def get_queryset(self, *args, **kwargs ):
        request = self.request
        return TwentyktoThirtyk_Mobile.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = TwentyktoThirtyk_Mobile.objects.all().featured()
    template_name = "TwentyktoThirtyk/featured-detail.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return product.objects.featured()

class ProductListView(ListView):
    #queryset = product.objects.all()
    template_name = "TwentyktoThirtyk/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args ** kwargs)
    #     print(context)
    #     return context

    def get_queryset(self, *args, **kwargs ):
        request = self.request
        return TwentyktoThirtyk_Mobile.objects.all()


def product_list_view(request):
    queryset = TwentyktoThirtyk_Mobile.objects.all()
    context = {
        "object_list": queryset
    }

    return render(request, "TwentyktoThirtyk/list.html", context)

class ProductDetailSlugView(DetailView):
    queryset = TwentyktoThirtyk_Mobile.objects.all()
    template_name = "TwentyktoThirtyk/detail.html"

    def get_context_data(self,*args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get("slug")
        #instance = get_object_or_404(product , slugs=slug, active=True)

        try:
            instance = TwentyktoThirtyk_Mobile.objects.get(slug=slug)
        except TwentyktoThirtyk_Mobile.DoesNotExist:
            raise Http404("Not found..")
        except TwentyktoThirtyk_Mobile.MultipleObjectsReturned:
            qs = TwentyktoThirtyk_Mobile.objects.filter(slug=slug)
            instance=qs.first()
        except:
            raise Http404("Uhmm")

        return instance

class ProductDetailView(DetailView):
    #queryset = product.objects.all()
    template_name = "TwentyktoThirtyk/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request =self.request
        pk = self.kwargs.get("pk")
        instance = TwentyktoThirtyk_Mobile.objects.get_by_id(pk)
        if instance is None:
            raise Http404("product doesn't exist")
        return instance

    # def get_queryset(self, *args, **kwargs ):
    #     request = self.request
    #     pk = self.kwargs.get("pk")
    #     return product.objects.filter(pk=pk)


def product_detail_view(request, pk=None, *args, **kwargs):
        #instance = product.objects.get(pk=pk, featured=True)
        #instance = get_object_or_404(product, pk=pk , featured=True)
    # try:
    #     instance =product.objects.get(id=pk)
    # except product.DoesNotExist:
    #     print('no products here')
    #     raise Http404("product does,not exist")
    # except:
    #     print("huh?")

    instance = TwentyktoThirtyk_Mobile.objects.get_by_id(pk)
    if instance is None:
        raise Http404("product doesn't exist")
    # print(instance)
    #
    # qs = product.objects.filter(id=pk)
    # if qs.exists() and qs.count() ==1:
    #     instance = qs.first()
    # else:
    #     raise Http404("product does,not exist")

    context = {
        "object": instance
    }
    return render(request, "TwentyktoThirtyk/detail.html", context)




@permission_required('admin.can_add_log_entry')
def Twentyk_to_Thirtyk_Mobile_product_upload(request):
    template = 'aproduct_upload.html'

    prompt = {
        'order': 'Order of our csv should be like your model'
    }


    if request.method == 'GET':
        return render(request, template , prompt)

    csv_file= request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request,"this is not a csv file")

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=",", quotechar="|" ):
       _, created = TwentyktoThirtyk_Mobile.objects.update_or_create(
            title = column[0],
            slug=column[1],
            price=column[2],
            Charging=column[3],
            Torch=column[4],
            Games=column[5],
            Messaging=column[6],
            Browser=column[7],
            Audio=column[8],
            Data=column[9],
            NFC=column[10],
            USB =column[11],
            GPS=column[12],
            Bluetooth=column[13],
            Wifi=column[14],
            Front=column[15],
            Main=column[16],
            card=column[17],
            BuiltIn=column[18],
            Features=column[19],
            Protection=column[20],
            Resolution=column[21],
            Size=column[22],
            Technology=column[23],
            GPU=column[24],
            Chipset=column[25],
            CPU=column[26],
            FourGBand=column[27],
            ThreeGBand=column[28],
            TwoGBand=column[29],
            Color=column[30],
            SIM=column[31],
            Weight=column[32],
            Dimension=column[33],
            UIBuild=column[34],
            OperatingSystem=column[35],
            image=column[36],
            image1=column[37],
            image2=column[38],
            Review_count=column[39],
            Average_Rating=column[40],
            Reviews=column[41],
            Ram=column[42],

        )

    context ={}
    return render(request, template, context)

TwentyktoThirtyk/templates/TwentyktoThirtyk/list.html
{% extends "base.html" %}
{% url "aproducts:list" as aproduct_list_url %}
{% url "samsungproducts:list" as samsungproduct_list_url %}
{% url "huaweiproducts:list" as aproduct_list_url %}
{% url "One_GB_Mobiles:list" as One_GB_Mobiles_list_url %}
{% url "Two_GB_Mobiles:list" as One_GB_Mobiles_list_url %}
{% url "Three_GB_Mobiles:list" as One_GB_Mobiles_list_url %}
{% url "FivektoTenk:list" as FivektoTenk_list_url %}
{% url "TenktoTwentyk:list" as TenktoTwentyk_list_url %}
{% url "TwentyktoThirtyk:list" as TwentyktoThirtyk_list_url %}

{% url "FiveMPMobile:list" as FiveMPMobiles_list_url %}
{% url "EightMPMobile:list" as EightMPMobiles_list_url %}
{% url "TwelveMPMobile:list" as TwelveMPMobiles_list_url %}





{% block content %}
    <h1 style="text-align: center">Mobiles Ranging in 20000 to 30000</h1>
<div class="container" style="width: 17%;height: 1550px;float: left;background-color: lavender;margin-left: 0px">



{#        <button style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 20px">Search By Ram</button>#}
{#        <button style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 20px">Search By Camera</button>#}
            <button  style="background-color: white;color: black;width: 250px;height:50px;margin-top: 10px">
                <a style="color: black;width: 250px;height:50px " href="{% url 'aproducts:list' %}"><b>Search by Brand</b></a>
        </button>
            <button style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 10px">
            <a style="color: white;width: 250px;height:50px " href="{% url 'aproducts:list' %}" href="{% url 'aproducts:list' %}">Apple</a>
        </button>
        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="color: white;width: 250px;height:50px " href="{% url 'samsungproducts:list' %}">Samsung</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'huaweiproducts:list' %}">Huawei</a>
        </button>
        <button  style="background-color: white;color: black;width: 250px;height:50px;margin-top: 10px">
            <b>Search by Ram</b>
        </button>
        {% include "searchram/snippets/search_form.html" with instance=obj %}

    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'One_GB_Mobiles:list' %}">1GB</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'Two_GB_Mobiles:list' %}">2GB</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'Three_GB_Mobiles:list' %}">3GB</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'aproducts:list' %}">4GB or above</a>
        </button>

        <button style="background-color: white;color: black;width: 250px;height:50px;padding-left: 0px;margin-top: 10px"><b>Search By Price</b></button>
            {% include "searchprice/snippets/search_form.html" with instance=obj %}

        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'FivektoTenk:list' %}"> > 10000</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'TenktoTwentyk:list' %}">10000 -- 20000</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'TwentyktoThirtyk:list' %}">20000 -- 30000</a>
        </button>
    <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'aproducts:list' %}">< 30000 </a>
        </button>


    <button  style="background-color: white;color: black;width: 250px;height:50px;margin-top: 10px">
        <a style="color:black;width: 250px;height:50px " href="{% url 'aproducts:list' %}"><b>Search by Camera</b></a>
        </button>
                                 {% include "searchprice/snippets/search_form.html" with instance=obj %}

        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'FiveMPMobile:list' %}"> 5MP </a>
        </button>
        <br>
        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'EightMPMobile:list' %}"> 8MP </a>
        </button>
        <br>
        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'TwelveMPMobile:list' %}"> 12MP </a>
        </button>
        <br>
        <button  style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px;margin-top: 5px">
            <a style="background-color: rgb(35, 47, 62);color: white;width: 250px;height:50px " href="{% url 'aproducts:list' %}"> 12MP or above </a>
        </button>

        <!--{% include "searchknowledge/snippets/search_form.html" with instance=obj %}-->
    </div>

<div class="container" style="margin-top: 15px;padding-left: 90px">
        <div class="row">

{#    <div class="container">#}
{#        <h2>Carousel Example</h2>#}
{#        <div id="myCarousel" class="carousel slide" data-ride="carousel">#}
{#            <!-- Indicators -->#}
{#            <ol class="carousel-indicators">#}
{#                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>#}
{#                <li data-target="#myCarousel" data-slide-to="1"></li>#}
{#                <li data-target="#myCarousel" data-slide-to="2"></li>#}
{#            </ol>#}
{#            <div class="carousel-inner">#}
{#                <div class="col">#}
                {% for obj in object_list %}
                    <div class="col">
{##}
{#                    {% if forloop.counter <= 3 %}#}
{##}
{#                                <div class="alert alert-success"></div>#}
{#                        <div class="item active col-md-4">#}
{##}
{#                            {% include "pproducts/snippets/card.html" with instance=obj %}#}
{#                    </div>#}
{#                        </div>#}
{#                    {% elif forloop.counter > 3 %}#}
{##}
{#                        <div class="item col-md-4">#}

                            {% include "TwentyktoThirtyk/snippets/card.html" with instance=obj %}
                        </div>
{##}
{#                    {% endif %}#}
{##}
                {% endfor %}
{#                                     </div>#}

            </div>

        </div>

{#            <!-- Left and right controls -->#}
{#        <a class="right carousel-control" href="#myCarousel" data-slide="next">#}
{#                <span class="glyphicon glyphicon-chevron-right"></span>#}
{#                <span class="sr-only">Next</span>#}
{#            </a>#}
{#            <a class="left carousel-control" href="#myCarousel" data-slide="prev">#}

{#    {% block basehead %}#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    {% endblock %}#}

{% endblock %}